import {AccompanyingPersonManage}  from "../business/AccompanyingPersonManage";
import {AccompanyingVehicleManage}  from "../business/AccompanyingVehicleManage";
import {GuestCalendar}  from "../business/GuestCalendar";
import { Inforleaving } from "./Inforleaving";
import { Car } from "./Car";
export class InfoInOut {
    id?: string;
    io_type?: boolean;
    inforleaving?: string;
    license_in?: string;
    license_out?: string;
    guestcalendar?: string;
    invited_person?: string;
    img_in?: string;
    img_out?: string;
    time_in?: Date;
    time_out?: Date;
    lane_id?: string;
    document_keep?: boolean;
    document_return?: boolean;
    document_return_img?: string;
    pri_car?: string;
    overview_in_img?: string;
    identification_in_img?: string;
    detail_in_img?: string;
    overview_out_img?: string;
    identification_out_img?: string;
    detail_out_img?: string;
    guestCalendarInfo: GuestCalendar;
    inforLeavingRequestInfo: Inforleaving;
    lstAccompanyingPersonManage: Array<AccompanyingPersonManage>;
    lstAccompanyingVehicleManage: Array<AccompanyingVehicleManage>;
    infoCar: Car;
    isModode?: string;
};
